# Generated by Django 3.2.4 on 2021-06-24 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('url', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('url', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('url', models.SlugField(unique=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('url', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('url', models.SlugField(unique=True)),
                ('Carousel', models.ImageField(blank=True, null=True, upload_to='')),
                ('Poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('ModifiedOn', models.DateTimeField(auto_now=True)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('AgeRating', models.PositiveSmallIntegerField()),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Series_Creators', to=settings.AUTH_USER_MODEL)),
                ('DeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Series_Deleters', to=settings.AUTH_USER_MODEL)),
                ('Genres', models.ManyToManyField(db_table='SeriesGenres', to='CSMain.Genre')),
                ('Languages', models.ManyToManyField(db_table='SeriesLanguages', to='CSMain.Language')),
                ('ModifiedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Series_Modifiers', to=settings.AUTH_USER_MODEL)),
                ('ProducedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CSMain.publisher')),
                ('Tags', models.ManyToManyField(db_table='SeriesTags', to='CSMain.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeasonNumber', models.PositiveSmallIntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('url', models.SlugField(unique=True)),
                ('Carousel', models.ImageField(blank=True, null=True, upload_to='')),
                ('Poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('ModifiedOn', models.DateTimeField(auto_now=True)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('AgeRating', models.PositiveSmallIntegerField()),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Season_Creators', to=settings.AUTH_USER_MODEL)),
                ('DeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Season_Deleters', to=settings.AUTH_USER_MODEL)),
                ('Genres', models.ManyToManyField(db_table='SeasonGenres', to='CSMain.Genre')),
                ('Languages', models.ManyToManyField(db_table='SeasonLanguages', to='CSMain.Language')),
                ('ModifiedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Season_Modifiers', to=settings.AUTH_USER_MODEL)),
                ('ParentSeries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CSMain.series')),
                ('Tags', models.ManyToManyField(db_table='SeasonTags', to='CSMain.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EpisodeNumber', models.PositiveSmallIntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('url', models.SlugField(unique=True)),
                ('Carousel', models.ImageField(blank=True, null=True, upload_to='')),
                ('Poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('ModifiedOn', models.DateTimeField(auto_now=True)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('AgeRating', models.PositiveSmallIntegerField()),
                ('isFree', models.BooleanField(default=False)),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Episode_Creators', to=settings.AUTH_USER_MODEL)),
                ('DeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Episode_Deleters', to=settings.AUTH_USER_MODEL)),
                ('Genres', models.ManyToManyField(db_table='EpisodeGenres', to='CSMain.Genre')),
                ('Languages', models.ManyToManyField(db_table='EpisodeLanguages', to='CSMain.Language')),
                ('ModifiedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Episode_Modifiers', to=settings.AUTH_USER_MODEL)),
                ('ParentSeason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CSMain.season')),
                ('Tags', models.ManyToManyField(db_table='EpisodeTags', to='CSMain.Tag')),
            ],
        ),
    ]
